name: 'Cache Dependencies'
description: 'Get the npm dependencies and cache them.'

runs:
  using: composite
  steps:
    - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cached-project-dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci