name: Build and Deploy Dev
on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Install Node and it's dependencies
        uses: ./.github/actions/cache-deps

      - name: Run Build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          ls
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/vue-practice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vue-practice:latest

    # deploy-dev:
