name: First Workflow
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit
