name: Playwright Tests
on:
  workflow_dispatch:

env:
  USER_NAME: ${{ secrets.USER_NAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  APP_URL: http://localhost:4173

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Install Node and it's dependencies
        uses: ./.github/actions/cache-deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Build
        run: npm run build
      - name: Run prod build app locally
        run: npm run preview &
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
